### ISSUE TITLE
When Can i expect Mongo Db source connector.?

### ISSUE THREAD

**Issue by nathgopi45** [datamountaineer/docs#13]
I have successfully completed with Mongo Db sink connector and it is working fine. Currently, we are expecting the same fo Mongo Db source connector. Kindly do the needful.

**Comment by andrewstevenson** [comment]
@nathgopi45  At the moment a mongodb source is not on our roadmap, obviously this can be changed but it would be on a commercial basis. Send me an email if you would like to discuss further.

**Comment by stheppi** [comment]
there is already a source for mongo: https://github.com/DataReply/kafka-connect-mongodb
