### ISSUE TITLE
[Poor performance] Kafka connect source with cassandra. High CPU consuming (even without process any row)

### ISSUE THREAD

**Issue by jjimenezcapi** [datamountaineer/docs#15]
It's normal a constant CPU use (by the kafka connect cassandra source process) around 50 - 60 % even without retrieve/proccess any row ? What could be happend ? I have indicated  configuration and profiling images.

Properties:

        connect.cassandra.assigned.tables = mytable
        connect.cassandra.contact.points = xx.yy.aa.bb
        connect.cassandra.error.policy = THROW
        connect.cassandra.import.mode = incremental
        connect.cassandra.import.poll.interval = 60000
        connect.cassandra.import.source.allow.filtering = true
        connect.cassandra.key.space = mykeyspace
        connect.cassandra.key.store.password = [hidden]
        connect.cassandra.key.store.path =
        connect.cassandra.max.retires = 20
        connect.cassandra.password = [hidden]
        connect.cassandra.port = 9042
        connect.cassandra.retry.interval = 60000
        connect.cassandra.source.kcql = INSERT INTO topic SELECT * FROM mytable PK ts
        connect.cassandra.source.task.batch.size = 100
        connect.cassandra.source.task.buffer.size = 10000
        connect.cassandra.ssl.client.cert.auth = false
        connect.cassandra.ssl.enabled = false
        connect.cassandra.trust.store.password = [hidden]
        connect.cassandra.trust.store.path =
        connect.cassandra.username = cassandra

![image](https://cloud.githubusercontent.com/assets/20641702/22778274/b56d2e94-eeb6-11e6-85b3-84c9e051a411.png)
![image](https://cloud.githubusercontent.com/assets/20641702/22778400/183f3c24-eeb7-11e6-8423-52ad04f065ff.png)
![image](https://cloud.githubusercontent.com/assets/20641702/22778150/3093daec-eeb6-11e6-9179-ed99255fc269.png)
![image](https://cloud.githubusercontent.com/assets/20641702/22778261/a2f278be-eeb6-11e6-9adb-a50e0e8fc7bf.png)

**Comment by andrewstevenson** [comment]
Fixed in stream reactor
