### ISSUE TITLE
Array support for InfluxDB sink connector

### ISSUE THREAD

**Issue by druhin-arrcus** [datamountaineer/docs#20]
Is there a reason why arrays aren't supported for the influxDB connector?

**Comment by stheppi** [comment]
please don't open the issues here.
You need to give us some context.  Which arrays, when arrays, why arrays :)

**Comment by druhin-arrcus** [comment]
I want to insert a record of the form:

```
{
	"a":[0,5.5],
	"b":["hi","bye"],
	"c":["ax","bx"],
	"d":149.213,
	"e":10.000,
	"f":"abc.com",
	"g":"if",
	"h":"ac0",
	"i":"lol",
	"j":""
}
```

Also, what is the proper forum to open issues?

**Comment by stheppi** [comment]
Influxdb doesn't have support for such a column type. If you look at their APi you will see it is handling primitive types. Now back on the array. What would you store it as. You can have an array of primitives or complex types comming through avro. Should it be stored as binary ? Text? What if null entries appear in thr array- would you save it or not?
This is not a functionality the sink should enforce. Your specific requirements might differ from others​. So it's the user responsibility to make sure the types meet Influxdb API
