### ISSUE TITLE
Socket error on client XXXXXXXXX, disconnecting.

### ISSUE THREAD

**Issue by AberamiGobekrishnan** [datamountaineer/docs#36]
Hi,
Initially the subscriber connects with the Mosquitto broker and gets the message from Publisher.And then Performs database Insertions and then the Connection to Subscriber gets disconnected...This happens repeatedly after every 2 database insertions..And the sbscriber cannot be restablished...Here the Publisher works Perfectly fine (by continously sending datas)...I have mentioned below the Subscriber code

connOpt = new MqttConnectOptions();
				client=new MqttClient("tcp://172.30.0.170:1885", MqttClient.generateClientId());
				client.setCallback(new FirstThread());
				connOpt.setCleanSession(true);
				connOpt.setUserName(M2MIO_USERNAME);
				connOpt.setPassword(M2MIO_PASSWORD_MD5.toCharArray());
				connOpt.setAutomaticReconnect(true);
				connOpt.setKeepAliveInterval(60);
				Logger.debug("Reconnect Option"+connOpt.isAutomaticReconnect());
				client.connect(connOpt);
				client.subscribe("iot_data",2);

And the error that is shown in Mosquitto Broker after 2 successful Insertions to the database 

New connection from 172.30.0.170 on port 1885.
1510823966: New client connected from 172.30.0.170 as paho105246605035518 (c1, k60, u'mosquitto').
1510823966: Sending CONNACK to paho105246605035518 (0, 0)
1510823966: Received SUBSCRIBE from paho105246605035518
1510823966:     iot_data (QoS 2)
1510823966: paho105246605035518 2 iot_data
1510823966: Sending SUBACK to paho105246605035518
1510823977: New connection from 34.207.210.198 on port 1885.
1510823977: New client connected from 34.207.210.198 as paho104607834163742 (c1, k30, u'mosquitto').
1510823977: Sending CONNACK to paho104607834163742 (0, 0)
1510823977: Received PUBLISH from paho104607834163742 (d0, q2, r0, m1, 'iot_data', ... (158 bytes))
1510823977: Sending PUBREC to paho104607834163742 (Mid: 1)
1510823977: Received PUBREL from paho104607834163742 (Mid: 1)
1510823977: Sending PUBCOMP to paho104607834163742 (Mid: 1)
1510823977: Sending PUBLISH to paho105246605035518 (d0, q2, r0, m1, 'iot_data', ... (158 bytes))
1510823977: Received PUBREC from paho105246605035518 (Mid: 1)
1510823977: Sending PUBREL to paho105246605035518 (Mid: 1)
1510823979: Received PUBCOMP from paho105246605035518 (Mid: 1)
1510823987: Received PUBLISH from paho104607834163742 (d0, q2, r0, m2, 'iot_data', ... (158 bytes))
1510823987: Sending PUBREC to paho104607834163742 (Mid: 2)
1510823987: Received PUBREL from paho104607834163742 (Mid: 2)
1510823987: Sending PUBCOMP to paho104607834163742 (Mid: 2)
1510823987: Sending PUBLISH to paho105246605035518 (d0, q2, r0, m2, 'iot_data', ... (158 bytes))
1510823987: Received PUBREC from paho105246605035518 (Mid: 2)
1510823987: Sending PUBREL to paho105246605035518 (Mid: 2)
1510823988: Received PUBCOMP from paho105246605035518 (Mid: 2)
1510823997: Received PUBLISH from paho104607834163742 (d0, q2, r0, m3, 'iot_data', ... (158 bytes))
1510823997: Sending PUBREC to paho104607834163742 (Mid: 3)
1510823997: Received PUBREL from paho104607834163742 (Mid: 3)
1510823997: Sending PUBCOMP to paho104607834163742 (Mid: 3)
1510823997: Sending PUBLISH to paho105246605035518 (d0, q2, r0, m3, 'iot_data', ... (158 bytes))
1510823997: Received PUBREC from paho105246605035518 (Mid: 3)
1510823997: Sending PUBREL to paho105246605035518 (Mid: 3)
1510824007: Received PUBLISH from paho104607834163742 (d0, q2, r0, m4, 'iot_data', ... (157 bytes))
1510824007: Sending PUBREC to paho104607834163742 (Mid: 4)
1510824007: Received PUBREL from paho104607834163742 (Mid: 4)
1510824007: Sending PUBCOMP to paho104607834163742 (Mid: 4)
1510824007: Sending PUBLISH to paho105246605035518 (d0, q2, r0, m4, 'iot_data', ... (157 bytes))
1510824007: **Socket error on client paho105246605035518, disconnecting.**

Any Solutions ?
Thanks in Advance.

**Comment by andrewstevenson** [comment]
@AberamiGobekrishnan Whats your connector configuration? Logs from Connect and version of the Stream reactor you are running?

This is also the docs repo.

**Comment by andrewstevenson** [comment]
@AberamiGobekrishnan No reply and on the wrong repo. Please raise on the stream reactor repo and provide the required info in the issue template
