### ISSUE TITLE
Unable to get any response after CURL 

### ISSUE THREAD

**Issue by mindfireon812** [datamountaineer/docs#9]
I am getting following output for curl in Kafka Socket Streamer
curl 'http://localhost:8080/sse/topics?topic=socket_streamer&consumergroup=testcg'
The requested resource could not be found

Also can anyone guide me , should I use this curl command.I have also tried this in browser ,still not getting any response.

Here is my consoles for data streamer
confluent3.0.1/stream-reactor/kafka-socket-streamer$ java -Dconfig.file=application.conf -jar build/libs/kafka-socket-streer-0.2.2-3.0.1-all.jar
2016-11-07 16:16:00,332 INFO  [main] [c.d.s.s.Main$] [delayedEndpoint$com$datamountaineer$streamreactor$socketstreamer$Main$1:36] 

    ____        __        __  ___                  __        _
   / __ \____ _/ /_____ _/  |/  /___  __  ______  / /_____ _(_)___  ___  ___  _____
  / / / / __ `/ __/ __ `/ /|_/ / __ \/ / / / __ \/ __/ __ `/ / __ \/ _ \/ _ \/ ___/
 / /_/ / /_/ / /_/ /_/ / /  / / /_/ / /_/ / / / / /_/ /_/ / / / / /  __/  __/ /
/_____/\__,_/\__/\__,_/_/  /_/\____/\__,_/_/ /_/\__/\__,_/_/_/ /_/\___/\___/_/
       _____            __        __  _____ __
      / ___/____  _____/ /_____  / /_/ ___// /_________  ____ _____ ___  ___  _____
      \__ \/ __ \/ ___/ //_/ _ \/ __/\__ \/ __/ ___/ _ \/ __ `/ __ `__ \/ _ \/ ___/
     ___/ / /_/ / /__/ ,< /  __/ /_ ___/ / /_/ /  /  __/ /_/ / / / / / /  __/ /
    /____/\____/\___/_/|_|\___/\__//____/\__/_/   \___/\__,_/_/ /_/ /_/\___/_/

by Andrew Stevenson
    
2016-11-07 16:16:00,338 INFO  [main] [c.d.s.s.Main$] [delayedEndpoint$com$datamountaineer$streamreactor$socketstreamer$Main$1:55] 
System name      : streamreactor-socket-streamer
Kafka brokers    : localhost:9092
Zookeepers       : localhost:2181
Schema registry  : http://localhost:8081
Listening on port : 8080
    
2016-11-07 16:16:00,922 INFO  [default-akka.kafka.default-dispatcher-7] [o.a.k.c.c.i.AbstractCoordinator] [handleGroupMetadataResponse:505] Discovered coordinator localhost:9092 (id: 2147483647 rack: null) for group datamountaineer.
Started

**Comment by andrewstevenson** [comment]
The docs aren't up-to-date for the socket streamer. Checkout the socket streamer section in this https://github.com/datamountaineer/kafka-connect-query-language/blob/master/README.md
________________________________

**Comment by mindfireon812** [comment]
Followed the same link mentioned.
Still facing issue.

**Comment by andrewstevenson** [comment]
So what's you KCQL query that you post in?

**Comment by andrewstevenson** [comment]
Issue solved?

**Comment by andrewstevenson** [comment]
?

**Comment by stheppi** [comment]
No reply, i assume there is no issue anymore.
Furthermore socket streamer is not supported anymore.
